module.exports = {
  settings: {
    Whitelist: [],
    DiscordPrefixText: null,
    DiscordPrefix: false,
    WAGroupPrefix: false,
    UploadAttachments: true,
    Token: '',
    GuildID: '',
    Categories: [],
    ControlChannelID: '',
    LocalDownloads: false,
    LocalDownloadMessage: 'Downloaded a file larger than the upload limit, check it out at {url}',
    DownloadDir: './downloads',
    DiscordFileSizeLimit: 8 * 1024 * 1024,
    LocalDownloadServer: false,
    LocalDownloadServerHost: 'localhost',
    LocalDownloadServerPort: 8080,
    Publish: false,
    ChangeNotifications: false,
    autoSaveInterval: 5 * 60,
    lastMessageStorage: 500,
    oneWay: 0b11,
    redirectWebhooks: false,
    DeleteMessages: true,
  },
  dcClient: null,
  waClient: null,
  chats: {},
  contacts: {},
  startTime: 0,
  logger: null,
  lastMessages: null,
  /**
   * Stores WhatsApp message IDs that originate from Discord so that
   * they are not echoed back to Discord when received from WhatsApp.
   */
  sentMessages: new Set(),
  goccRuns: {},
  updateInfo: null,
  version: '',
};
